---
ignored:
  - DL3008
# label-schema:                           # See Linting Labels below for specific label-schema details
#   author: "Quien Sabe"                        # Your name
#   contact: qs5779@mail.com                       # email address
# #   # created: timestamp                    # rfc3339 datetime
# #   # version: string                       # semver
# #   # documentation: string                 # url
# #   # git-revision: string                  # hash
# #   license: MIT                       # spdx
trustedRegistries:
  - docker.io
...
# vim:ts=2:ft=yml
