---
name: amd64 Branch CI

# from https://github.com/metcalfc/docker-action-examples/blob/main/app/Dockerfile
# For all pushes to the edge branch run the tests and push the image to the
# GitHub registry under an edge tag so we can use it for the nightly
# integration tests
on:
  push:
    branches:
      - 'arch-[0-9].[0-9]+.[0-9]+'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      # GitHub Actions do not automatically checkout your projects. If you need the code
      # you need to check it out.
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get image info
        id: imageinfo
        shell: bash
        run: |
          echo "pyversion=$(echo "${GITHUB_REF##*/}" | cut -f 2 -d '-')" >> $GITHUB_OUTPUT
          echo "distronm=$(echo "${GITHUB_REF##*/}" | cut -f 1 -d '-')" >> $GITHUB_OUTPUT

      - name: Prepare
        id: prep
        run: |
          DTAG=${{ steps.imageinfo.outputs.distronm }}-${{ steps.imageinfo.outputs.pyversion }}
          DOCKER_TAGS=qs5779/python-testing:${DTAG}
          GHCR_TAGS=ghcr.io/$DOCKER_TAGS
          echo "dockertags=${DOCKER_TAGS}" >> $GITHUB_OUTPUT
          echo "ghcrtags=${GHCR_TAGS}" >> $GITHUB_OUTPUT

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Github Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.WTF_ONE_FREE }}

      - name: Login to Github Container Repository
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./src
          file: ./src/Dockerfile.${{ steps.imageinfo.outputs.distronm }}
          build-args: PY_VERSION=${{ steps.imageinfo.outputs.pyversion }}
          push: ${{ github.event_name != 'pull_request' }}
          platforms: linux/amd64
          tags: ${{ steps.prep.outputs.dockertags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - # run tests using image from docker hub
        name: Run Tests
        run: DTAG=$(echo ${{ steps.prep.outputs.dockertags }} | tr ',' ' ') make test

      - # copy multiplatform image from dockerhub to ghcr
        name: Push Image to multiple registries
        uses: akhilerm/tag-push-action@v2.1.0
        with:
          src: ${{ steps.prep.outputs.dockertags }}
          dst: ${{ steps.prep.outputs.ghcrtags }}
...
