---
name: ubuntu Branch CI

# from https://github.com/metcalfc/docker-action-examples/blob/main/app/Dockerfile
# For all pushes to the edge branch run the tests and push the image to the
# GitHub registry under an edge tag so we can use it for the nightly
# integration tests
on:
  push:
    branches:
      - 'ubuntu-[0-9].[0-9]+.[0-9]+'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      # GitHub Actions do not automatically checkout your projects. If you need the code
      # you need to check it out.
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get branch name (merge)
        if: github.event_name != 'pull_request'
        shell: bash
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})"
      - name: Get python version
        if: github.event_name != 'pull_request'
        shell: bash
        run: echo "PY_VERSION=$(echo ${{ env.BRANCH_NAME }} | sed -e 's/^ubuntu-//')"
      - name: Prepare
        id: prep
        run: |
          DOCKER_TAGS=qs5779/python-testing:${{ env.BRANCH_NAME }}
          GHCR_TAGS=ghcr.io/$DOCKER_TAGS
          echo ::set-output name=dockertags::${DOCKER_TAGS}
          echo ::set-output name=ghcrtags::${GHCR_TAGS}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Github Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.WTF_ONE_FREE }}

      - name: Login to Github Container Repository
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./src
          file: ./src/Dockerfile
          build-args: PY_VERSION=${{ env.PY_VERSION }}
          push: ${{ github.event_name != 'pull_request' }}
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.prep.outputs.dockertags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - # run tests using image from docker hub
        name: Run Tests
        run: TAGS=$(echo ${{ steps.prep.outputs.dockertags }} | tr ',' ' ') make test

      - # copy multiplatform image from dockerhub to ghcr
        name: Push Image to multiple registries
        uses: akhilerm/tag-push-action@v2.1.0
        with:
          src: ${{ steps.prep.outputs.dockertags }}
          dst: ${{ steps.prep.outputs.ghcrtags }}
...
